version: '3'

services:
  web:
    container_name: my_scrap
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo  # Set the hostname to the service name of the MongoDB container
      MONGO_PORT: 27017
      MONGO_URI: "mongodb://mongo:27017/"
      DB_NAME: "my_database"
      COLLECTION_NAME: "facebook_posts"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
